@startuml
class Cart {
  -id : CustomerId
  +addProduct(product : Product, quantity : int)
}

Cart *-  CartLineItem

class CartLineItem {
  -quantity : int
  +increaseQuantityBy(value : int)
}

CartLineItem -> Product

class Product {
  -id : ProductId
  -name : String
  -description : String
  -itemsInStock : int
}

Product --> Money : price

class Money {
  -currency : Currency
  -amount : BigDecimal
}
@enduml